version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    depends_on:
    - mqtt
    healthcheck:
      test: "curl -Lf http://localhost:8123 || exit 1"
      interval: 15s
      timeout: 15s
      retries: 10

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    network_mode: host

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    depends_on:
    - mqtt
    volumes:
    - ./zigbee2mqtt/data:/app/data
    - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
#    privileged: true
    environment:
      - TZ=Europe/Copenhagen
