automation:
- alias: "[Entrance] Trigger light on motion"
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_motion_sensor
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.entrance_light
      kelvin: 2700
      brightness_pct: 100
      transition: 1
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.entrance_motion_sensor
      to: 'off'
  - delay: '00:01:00'
  - service: light.turn_on
    data:
      entity_id: light.entrance_light
      brightness_pct: 0
      transition: 15
