input_select:
  guest_room_lights:
    options:
    - 'off'
    - evening

automation:
- alias: "[Guest room] Pass on lights mode"
  variables:
    map:
      off: 'off'
      day: 'off'
      evening: evening
      bedtime: evening
      night: 'off'
  condition:
    condition: state
    entity_id: input_boolean.guests
    state: 'off'
  trigger:
    platform: state
    entity_id: input_select.lights_mode
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.guest_room_lights
      option: "{{ map[states('input_select.lights_mode')] }}"

- alias: "[Guest room] Activate scene"
  trigger:
    platform: state
    entity_id: input_select.guest_room_lights
  action:
  - service: scene.turn_on
    data:
      entity_id: "{{ 'scene.guest_room_' ~ states('input_select.guest_room_lights') }}"
      transition: 10
