automation:
  
  # Lights_mode = bedtime.

  - alias: Turn on hallway light when lights mode changes to bedtime.
    trigger:
      platform: state
      entity_id: input_select.lights_mode
      to: 'bedtime'
    action:
      - service: light.turn_on
        data:
          entity_id: light.hallway_light
          kelvin: 2200
          brightness_pct: 100
          transition: 15   
      - service: timer.cancel
        data:
          entity_id: timer.hallway

  # Lights_mode = night.

  - alias: Turn off hallway light when lights mode changes to night.
    trigger:
      platform: state
      entity_id: input_select.lights_mode
      to: "night"
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.hallway_light
          kelvin: 2200
          brightness_pct: >
            {% if is_state("input_boolean.guests", "night") %}
              5
            {% else %}
              0
            {% endif %}
          transition: 15   
      - service: timer.cancel
        data:
          entity_id: timer.hallway

timer:
  hallway:
    duration: '00:02:00'
