input_select:
  lights_mode:
    name: Lights mode
    options:
      - 'off'
      - morning
      - day
      - evening
      - bedtime
      - night

sensor:
- platform: template
  sensors:
    sun_elevation:
      friendly_name: "Sun Elevation"
      unit_of_measurement: "°"
      value_template: "{{ state_attr('sun.sun','elevation') }}"      

automation:
- alias: Set lights mode to 'day' when day mode is set to 'day'
  trigger:
    platform: state
    entity_id: input_select.day_mode
    to: 'day'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.lights_mode
      option: 'day'

- alias: "Lights mode automation"
  variables:
    settings:
      morning:        
        wardrobe_light:         [   0, 2200 ]

      evening:
        wardrobe_light:         [   0, 2200 ]
                      
      bedtime:
        wardrobe_light:         [ 100, 2200 ]

      night:
        wardrobe_light:         [   0, 2200 ]
  
  trigger:
    platform: state
    entity_id: input_select.lights_mode
  condition:
    - "{{ states('input_select.lights_mode') in settings }}"
  action:
    repeat:
      while: "{{ repeat.index <= settings[ states('input_select.lights_mode') ] | length }}"
      sequence:
      - variables:          
          lights_mode: "{{ states('input_select.lights_mode') }}"
          entity_id: "{{ ( settings[ lights_mode ].keys()|list )[ repeat.index - 1] }}"
          brightness_pct: "{{ ( settings[ lights_mode ].values()|list )[ repeat.index - 1][0] }}"
          kelvin: "{{ ( settings[ lights_mode ].values()|list )[ repeat.index - 1][1] or 2700 }}"
          transition: "{{ ( settings[ lights_mode ].values()|list )[ repeat.index - 1][2] or 15 }}"
      - service: light.turn_on
        data:
          entity_id: "{{ 'light.' ~ entity_id }}"
          brightness_pct: "{{ brightness_pct }}"
          kelvin: "{{ kelvin }}"
          transition: "{{ transition }}"
