input_select:
  lights_mode:
    name: Lights mode
    options:
      - 'off'
      - morning
      - day
      - evening
      - bedtime
      - night

sensor:
- platform: template
  sensors:
    sun_elevation:
      friendly_name: "Sun Elevation"
      unit_of_measurement: "°"
      value_template: "{{ state_attr('sun.sun','elevation') }}"      
