- id: '1620242106419'
  alias: Motion light - Hallway - 1 morning
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hallway_motion_sensor
      scene_on: scene.hallway_on_evening
      scene_off: scene.hallway_dimmed
      lights_mode: morning
- id: '1620240236151'
  alias: Motion light - Hallway - 2 evening
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hallway_motion_sensor
      scene_on: scene.hallway_on_evening
      scene_off: scene.hallway_dimmed
      lights_mode: evening
- id: '1620242803731'
  alias: Motion light - Hallway - 3 night
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hallway_motion_sensor
      scene_on: scene.hallway_dimmed
      scene_off: scene.hallway_off
      wait_time: 0
      lights_mode: night
