
homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  media_dirs:
    local: /local-media
  external_url: "https://ha.jkbb.dk"
  internal_url: "http://ha-local.borg.cc:8123"
  country: DK

default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 172.17.0.0/24

logger:
  default: info

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

input_boolean: 
  guests:
    name: Guests
    icon: mdi:account-multiple
    initial: off
  presence:
    name: Presence
    icon: mdi:tools
    initial: off
  morning_alarm:
    name: Morning alarm
    initial: on
  vacation:
    name: Vacation
    initial: off
  winter_lights:
    name: Winter lights
    initial: off

input_select:

  radio_station:
    name: Radio station
    options:
    - DR P1
    - DR P3
    - DR P4
    - DR P6 Beat

# Resources

lovelace:
  resources:
  - url: /local/mini-media-player-bundle.js?v=1.16.5
    type: module
  - url: /local/slider-entity-row.js
    type: module
