- platform: template
  sensors:
    living_room_temperature:
      friendly_name: "Living room temperature"
      value_template: "{{ state_attr('climate.living_room', 'current_temperature') }}"
      unit_of_measurement: "°C"
